hellooooddd

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,68 +1,56 @@
-stages:
-  - build
-  - test
-  - release
-  - deploy
+image: docker:20.10.17
 
-build-job:
-  tags:
-    - docker
-  stage: build
-  script:
-    - echo "creating virtual environment for the project..."
-    - virtualenv $(pwd)/venv
-    - source $(pwd)/venv/bin/activate
-    - echo "Installing requirements..."
-    - pip install -r base.txt
-    - pip install -r local.txt
-    - pip install -r production.txt
-    - deactivate
-  artifacts:
-    paths:
-      - $(pwd)/venv
-
-test-job:
-  tags:
-    - docker
-  stage: test
-  script:
-    - echo "Activating virtual environment..."
-    - source $(pwd)/venv/bin/activate
-    - echo "Running unit tests..."
-    - python manage.py test budget
-    - echo "Checking the server..."
-    - python manage.py runserver &
-    - sleep 10
-    - curl -sSf http://localhost:8000 > /dev/null && echo "Server is Up"
-    - sudo pkill python
-    - deactivate
-    - echo "All tests successfully passed."
+services:
+  - docker:20.10.17-dind
 
 variables:
-  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID
+  DOCKER_TLS_CERTDIR: "/certs"
 
-release-job:
-  tags:
-    - docker
-  stage: release
-  before_script:
+stages:
+  - build
+
+dev_build_image:
+  stage: build
+  script:
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
-  script:
-    - docker build -t $CONTAINER_IMAGE .
-    - docker push $CONTAINER_IMAGE
-  after_script:
-    - docker logout
+    - docker build -t $CI_REGISTRY_IMAGE:dev-latest .
+    - docker push $CI_REGISTRY_IMAGE:dev-latest
 
-# Deploy petclinic
-deploy-job:
-  tags:
-    - docker
-  stage: deploy
+  rules:
+    - if: $CI_COMMIT_REF_NAME == "dev"
+    - changes:
+        - Dockerfile
 
+staging_build_image:
+  stage: build
   script:
-    - echo "Logging in to Docker Hub"
-    - docker login -u walidmbarek -p walid123$
-    - echo "Building Docker image"
-    - docker build -t walidmbarek/djangobackend .
-    - echo "Pushing Docker image to Docker Hub"
-    - docker push walidmbarek/djangobackend
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+    - if [[ "$CI_COMMIT_REF_NAME" == "staging" && "$CI_COMMIT_TITLE" =~ ^stg-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+        docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TITLE .;
+        docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TITLE;
+      else
+        echo "Invalid staging branch commit message. Build failed.";
+        exit 1;
+      fi
+
+  rules:
+    - if: $CI_COMMIT_REF_NAME == "staging"
+    - changes:
+        - Dockerfile
+
+production_build_image:
+  stage: build
+  script:
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+    - if [[ "$CI_COMMIT_REF_NAME" == "main" && "$CI_COMMIT_TITLE" =~ ^prod-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+        docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TITLE .;
+        docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TITLE;
+      else
+        echo "Invalid production branch commit message. Build failed.";
+        exit 1;
+      fi
+
+  rules:
+    - if: $CI_COMMIT_REF_NAME == "main"
+    - changes:
+        - Dockerfile
